global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8081']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
