global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    dns_sd_configs:
      - names: ['tasks.node-exporter']
        type: A
        port: 9100

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: A
        port: 8080

  - job_name: 'backend'
    dns_sd_configs:
      - names: ['tasks.backend']
        type: A
        port: 8081

  - job_name: 'redis'
    dns_sd_configs:
      - names: ['tasks.redis-exporter']
        type: A
        port: 9121
